[project]
name = "odoo-addons-oca-sign"
version = "18.0.20250113.0"
dependencies = [
    "odoo-addon-sign_oca==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
